import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import AuthInitializer from "@/components/AuthInitializer/AuthInitializer";
import CartPreview from "@/components/CartPreview/CartPreview";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

// const anton = Anton({
//   subsets: ["latin"],
//   weight: "400",
//   variable: "--font-anton",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // other: {
  //   timeZone: "Europe/Kyiv",
  // },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <Providers>
          <AuthInitializer />
          {children}
          <CartPreview />
        </Providers>
      </body>
    </html>
  );
}
